server:
  port: 8002

spring:
  application:
    name: class-booking-service
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.gym: DEBUG
